version: "3.7"
volumes:
  postgres:
  init:
services:
  postgres:
    image: postgres:latest
    environment:
     - POSTGRES_USER=docker_chad
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=postgres
    volumes:

     - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:54320:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U docker_chad -d postgres" ]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s
    restart: always


#  api_service:
#    build: .
#
#    ports:
#      - "8080:8080"
#
#    environment:
#      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
##      - /basics?allowPublicKeyRetrieval=true
#    depends_on:
#       postgres:
#         condition: service_healthy

#    volumes:
#      - .m2:/root/.m2




